set(wxCORELIB_NAME wxcore)

# needed packages
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/src/jpeg)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/src/tiff/libtiff)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/src/png)

set(COMMON_CSOURCES
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/accelcmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/accesscmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/affinematrix2d.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/anidecod.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/appcmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/artprov.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/artstd.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/arttango.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/bmpbase.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/bmpbtncmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/bookctrl.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/btncmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/cairo.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/checkboxcmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/checklstcmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/choiccmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/clipcmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/clrpickercmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/cmdproc.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/cmndata.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/colourcmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/colourdata.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/combocmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/containr.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/cshelp.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/ctrlcmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/ctrlsub.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/dcbase.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/dcbufcmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/dcgraph.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/dcsvg.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/dirctrlcmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/dlgcmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/dndcmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/dobjcmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/docmdi.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/docview.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/dpycmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/dseldlg.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/dummy.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/effects.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/event.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/fddlgcmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/filectrlcmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/filehistorycmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/filepickercmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/fldlgcmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/fontcmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/fontdata.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/fontenumcmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/fontmap.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/fontpickercmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/fontutilcmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/framecmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/fs_mem.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/gaugecmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/gbsizer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/gdicmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/geometry.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/gifdecod.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/graphcmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/headercolcmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/headerctrlcmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/helpbase.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/iconbndl.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/imagall.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/imagbmp.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/image.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/imagfill.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/imaggif.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/imagiff.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/imagjpeg.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/imagpcx.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/imagpng.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/imagpnm.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/imagtga.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/imagtiff.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/imagxpm.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/layout.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/lboxcmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/listctrlcmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/markupparser.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/matrix.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/menucmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/mousemanager.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/msgout.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/nbkbase.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/overlaycmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/ownerdrwcmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/panelcmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/paper.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/persist.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/pickerbase.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/popupcmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/prntbase.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/quantize.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/radiobtncmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/radiocmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/rearrangectrl.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/rendcmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/rgncmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/scrolbarcmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/settcmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/sizer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/slidercmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/spinbtncmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/spinctrlcmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/srchcmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/statbar.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/statbmpcmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/statboxcmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/statlinecmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/stattextcmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/stockitem.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/tbarbase.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/textcmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/textentrycmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/toplvcmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/treebase.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/uiactioncmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/utilscmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/valgen.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/validate.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/valnum.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/valtext.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/wincmn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/windowid.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/wrapsizer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/common/xpmdecod.cpp
)

source_group("Common Sources" FILES ${COMMON_CSOURCES})

set( MSW_CSOURCES
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/accel.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/ole/access.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/ole/activex.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/anybutton.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/app.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/artmsw.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/ole/automtn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/bitmap.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/bmpbuttn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/brush.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/button.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/caret.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/checkbox.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/checklst.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/choice.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/clipbrd.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/colordlg.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/colour.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/combo.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/combobox.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/control.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/cursor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/data.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/ole/dataobj.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/dc.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/dcclient.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/dcmemory.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/dcprint.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/dcscreen.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/dialog.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/dialup.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/dib.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/dirdlg.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/display.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/dragimag.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/ole/dropsrc.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/ole/droptgt.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/enhmeta.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/evtloop.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/fdrepdlg.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/filedlg.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/font.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/fontdlg.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/fontenum.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/fontutil.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/frame.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/gauge.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/gdiimage.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/gdiobj.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/gdiplus.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/graphics.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/headerctrl.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/helpchm.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/helpwin.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/icon.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/imaglist.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/iniconf.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/listbox.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/listctrl.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/main.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/mdi.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/menu.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/menuitem.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/metafile.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/minifram.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/msgdlg.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/mslu.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/nativdlg.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/nativewin.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/notebook.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/nonownedwnd.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/ole/oleutils.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/ownerdrw.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/palette.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/panel.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/pen.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/popupwin.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/printdlg.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/printwin.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/progdlg.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/radiobox.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/radiobut.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/region.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/renderer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/richmsgdlg.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/scrolbar.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/settings.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/slider.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/spinbutt.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/spinctrl.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/statbmp.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/statbox.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/statline.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/stattext.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/statusbar.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/textctrl.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/textentry.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/tglbtn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/toolbar.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/tooltip.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/toplevel.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/treectrl.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/uiaction.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/utilsgui.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/ole/uuid.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/uxtheme.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/volume.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/window.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/msw/version.rc
)
source_group("MSW Sources" FILES ${MSW_CSOURCES})

set(GEN_CSOURCES
    #${CMAKE_CURRENT_SOURCE_DIR}/src/generic/accel.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/busyinfo.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/buttonbar.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/choicbkg.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/choicdgg.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/clrpickerg.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/collpaneg.cpp
    #${CMAKE_CURRENT_SOURCE_DIR}/src/generic/colrdlgg.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/combog.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/dcpsg.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/dirctrlg.cpp
    #${CMAKE_CURRENT_SOURCE_DIR}/src/generic/dirdlgg.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/dragimgg.cpp
    #${CMAKE_CURRENT_SOURCE_DIR}/src/generic/fdrepdlg.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/filectrlg.cpp
    #${CMAKE_CURRENT_SOURCE_DIR}/src/generic/filedlgg.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/filepickerg.cpp
    #${CMAKE_CURRENT_SOURCE_DIR}/src/generic/fontdlgg.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/fontpickerg.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/graphicc.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/headerctrlg.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/infobar.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/listbkg.cpp
    #${CMAKE_CURRENT_SOURCE_DIR}/src/generic/listctrl.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/logg.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/markuptext.cpp
    #${CMAKE_CURRENT_SOURCE_DIR}/src/generic/mdig.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/msgdlgg.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/numdlgg.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/printps.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/prntdlgg.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/progdlgg.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/renderg.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/richmsgdlgg.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/scrlwing.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/selstore.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/spinctlg.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/splitter.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/srchctlg.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/statbmpg.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/stattextg.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/statusbr.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/textdlgg.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/tipwin.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/toolbkg.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/treebkg.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/treectlg.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/vlbox.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/generic/vscroll.cpp
    )
source_group("Generic Sources" FILES ${GEN_CSOURCES})

set(wxUniv_CSOURCES
    ${CMAKE_CURRENT_SOURCE_DIR}/src/univ/bmpbuttn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/univ/button.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/univ/checkbox.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/univ/checklst.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/univ/choice.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/univ/combobox.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/univ/control.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/univ/ctrlrend.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/univ/dialog.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/univ/framuniv.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/univ/gauge.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/univ/themes/gtk.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/univ/inpcons.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/univ/inphand.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/univ/listbox.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/univ/menu.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/univ/themes/metal.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/univ/themes/mono.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/univ/notebook.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/univ/radiobox.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/univ/radiobut.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/univ/scrarrow.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/univ/scrolbar.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/univ/scrthumb.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/univ/settingsuniv.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/univ/slider.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/univ/spinbutt.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/univ/statbmp.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/univ/statbox.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/univ/statline.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/univ/stattext.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/univ/statusbr.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/univ/stdrend.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/univ/textctrl.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/univ/tglbtn.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/univ/theme.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/univ/toolbar.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/univ/topluniv.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/univ/themes/win32.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/univ/winuniv.cpp
    )
source_group("wxUniv Sources" FILES ${wxUniv_CSOURCES})

set(MSW_HHEADERS
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/accel.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/ole/access.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/ole/activex.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/anybutton.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/app.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/ole/automtn.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/bitmap.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/bmpbuttn.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/bmpcbox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/brush.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/button.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/calctrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/caret.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/checkbox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/checklst.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/choice.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/clipbrd.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/colordlg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/colour.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/combo.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/combobox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/commandlinkbutton.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/control.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/ctrlsub.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/cursor.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/custombgwin.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/ole/dataform.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/ole/dataobj.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/ole/dataobj2.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/datectrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/datetimectrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/dc.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/dcclient.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/dcmemory.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/dcprint.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/dcscreen.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/dialog.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/dib.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/dirdlg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/dragimag.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/ole/dropsrc.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/ole/droptgt.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/enhmeta.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/evtloop.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/fdrepdlg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/filedlg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/font.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/fontdlg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/frame.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/gauge.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/gdiimage.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/genrcdefs.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/glcanvas.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/headerctrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/helpbest.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/helpchm.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/helpwin.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/htmlhelp.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/hyperlink.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/icon.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/imaglist.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/iniconf.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/init.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/joystick.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/listbox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/listctrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/mdi.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/menu.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/menuitem.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/metafile.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/minifram.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/missing.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/msgdlg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/msvcrt.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/nonownedwnd.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/notebook.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/notifmsg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/ole/oleutils.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/ownerdrw.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/palette.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/panel.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/pen.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/popupwin.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/printdlg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/printwin.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/progdlg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/radiobox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/radiobut.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/rcdefs.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/region.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/richmsgdlg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/scrolbar.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/slider.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/sound.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/spinbutt.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/spinctrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/statbmp.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/statbox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/statline.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/stattext.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/statusbar.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/taskbar.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/textctrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/textentry.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/tglbtn.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/timectrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/toolbar.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/tooltip.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/toplevel.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/treectrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/ole/uuid.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/uxtheme.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/uxthemep.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/webview_ie.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/webviewhistoryitem_ie.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/window.h
)    
source_group("MSW Headers" FILES ${MSW_HHEADERS})

set(GEN_HHEADERS
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/aboutdlgg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/accel.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/animate.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/bmpcbox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/busyinfo.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/buttonbar.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/calctrlg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/choicdgg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/clrpickerg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/collpaneg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/colrdlgg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/combo.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/ctrlsub.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/custombgwin.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/dataview.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/datectrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/dcpsg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/dirctrlg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/dirdlgg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/dragimgg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/dvrenderer.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/dvrenderers.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/fdrepdlg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/filectrlg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/filedlgg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/filepickerg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/fontdlgg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/fontpickerg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/grid.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/gridctrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/grideditors.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/gridsel.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/headerctrlg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/helpext.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/hyperlink.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/infobar.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/laywin.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/listctrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/logg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/mdig.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/msgdlgg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/notebook.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/notifmsg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/numdlgg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/panelg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/printps.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/prntdlgg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/progdlgg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/propdlg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/richmsgdlgg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/sashwin.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/scrolwin.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/spinctlg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/splash.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/splitter.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/srchctlg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/statbmpg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/stattextg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/statusbr.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/textdlgg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/timectrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/treectlg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/generic/wizard.h
    )    
source_group("Generic Headers" FILES ${GEN_HHEADERS})   

set(wxUniv_HHEADERS
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/anybutton.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/app.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/bmpbuttn.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/button.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/checkbox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/checklst.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/chkconf.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/choice.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/colschem.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/combobox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/control.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/custombgwin.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/dialog.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/frame.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/gauge.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/inpcons.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/inphand.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/listbox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/menu.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/menuitem.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/notebook.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/panel.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/radiobox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/radiobut.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/renderer.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/scrarrow.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/scrolbar.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/scrthumb.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/scrtimer.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/slider.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/spinbutt.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/statbmp.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/statbox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/statline.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/stattext.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/statusbr.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/stdrend.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/textctrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/tglbtn.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/theme.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/toolbar.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/toplevel.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/window.h 
)
source_group("wxUniv Headers" FILES ${wxUniv_HHEADERS}) 

set(wxHTML_HHEADERS
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/html/helpctrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/html/helpdata.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/html/helpdlg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/html/helpfrm.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/html/helpwnd.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/html/htmlcell.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/html/htmldefs.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/html/htmlfilt.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/html/htmlpars.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/html/htmlproc.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/html/htmltag.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/html/htmlwin.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/html/htmprint.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/html/m_templ.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/html/styleparams.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/html/winpars.h
)
source_group("wxHTML Headers" FILES ${wxHTML_HHEADERS}) 

set(COMMON_HHEADERS
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/aboutdlg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/accel.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/access.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/propgrid/advprops.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/affinematrix2d.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/affinematrix2dbase.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/anidecod.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/animate.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/animdecod.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/anybutton.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/ribbon/art.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/ribbon/art_internal.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/artprov.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/aui/aui.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/aui/auibar.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/aui/auibook.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/bannerwindow.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/ribbon/bar.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/bitmap.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/bmpbuttn.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/bmpcbox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/bookctrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/persist/bookctrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/brush.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/busyinfo.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/button.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/ribbon/buttonbar.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/cairo.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/calctrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/caret.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/checkbox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/checklst.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/choicdlg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/choice.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/choicebk.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/clipbrd.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/clrpicker.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/cmdproc.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/cmndata.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/collpane.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/colordlg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/colour.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/colourdata.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/combo.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/combobox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/commandlinkbutton.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/compositewin.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/control.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/ribbon/control.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/cshelp.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/ctrlsub.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/cursor.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/custombgwin.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/dataobj.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/dataview.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/datectrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/dateevt.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/datetimectrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/dc.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/dcbuffer.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/dcclient.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/dcgraph.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/dcmemory.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/dcmirror.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/dcprint.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/dcps.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/dcscreen.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/dcsvg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/debugrpt.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/dialog.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/dialup.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/dirctrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/dirdlg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/display.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/display_impl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/dnd.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/aui/dockart.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/docmdi.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/docview.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/dragimag.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/dvrenderers.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/editlbox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/propgrid/editors.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/effects.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/encinfo.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/evtloopsrc.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/fdrepdlg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/filectrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/filedlg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/filehistory.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/filepicker.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/aui/floatpane.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/fmappriv.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/font.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/fontdata.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/fontdlg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/fontenum.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/fontpicker.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/fontutil.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/frame.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/aui/framemanager.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/ribbon/gallery.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/gauge.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/gbsizer.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/gdicmn.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/gdiobj.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/geometry.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/gifdecod.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/glcanvas.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/graphics.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/grid.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/headercol.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/headerctrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/help.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/helpbase.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/helphtml.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/helpwin.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/htmllbox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/hyperlink.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/icon.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/iconbndl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/imagbmp.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/image.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/imaggif.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/imagiff.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/imagjpeg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/imaglist.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/imagpcx.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/imagpng.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/imagpnm.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/imagtga.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/imagtiff.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/imagxpm.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/infobar.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/itemid.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/joystick.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/layout.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/laywin.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/listbase.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/listbook.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/listbox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/listctrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/propgrid/manager.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/matrix.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/mdi.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/mediactrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/menu.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/menuitem.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/metafile.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/minifram.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/mousemanager.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msgdlg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/nativewin.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/nonownedwnd.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/notebook.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/notifmsg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/numdlg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/odcombo.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/overlay.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/ownerdrw.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/ribbon/page.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/palette.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/panel.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/ribbon/panel.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/paper.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/pen.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/persist.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/pickerbase.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/popupwin.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/position.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/print.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/printdlg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/prntbase.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/progdlg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/propdlg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/propgrid/property.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/propgrid/propgrid.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/propgrid/propgriddefs.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/propgrid/propgridiface.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/propgrid/propgridpagestate.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/propgrid/props.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/quantize.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/radiobox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/radiobut.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/range.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/rawbmp.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/rearrangectrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/region.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/renderer.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/richmsgdlg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/richtext/richtextbackgroundpage.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/richtext/richtextborderspage.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/richtext/richtextbuffer.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/richtext/richtextbulletspage.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/richtext/richtextctrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/richtext/richtextdialogpage.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/richtext/richtextfontpage.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/richtext/richtextformatdlg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/richtext/richtexthtml.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/richtext/richtextimagedlg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/richtext/richtextindentspage.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/richtext/richtextliststylepage.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/richtext/richtextmarginspage.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/richtext/richtextprint.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/richtext/richtextsizepage.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/richtext/richtextstyledlg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/richtext/richtextstylepage.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/richtext/richtextstyles.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/richtext/richtextsymboldlg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/richtext/richtextuicustomization.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/richtext/richtextxml.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/richtooltip.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/sashwin.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/scopeguard.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/scrolbar.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/scrolwin.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/selstore.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/settings.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/sizer.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/slider.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/sound.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/spinbutt.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/spinctrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/splash.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/persist/splitter.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/splitter.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/srchctrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/statbmp.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/statbox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/statline.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/stattext.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/statusbr.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/stc/stc.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/aui/tabart.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/aui/tabmdi.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/taskbar.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/tbarbase.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/textcompleter.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/textctrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/textdlg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/textentry.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/textwrapper.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/tglbtn.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/timectrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/tipdlg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/tipwin.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/ribbon/toolbar.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/toolbar.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/toolbook.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/tooltip.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/persist/toplevel.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/toplevel.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/treebase.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/persist/treebook.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/treebook.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/treectrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/treelist.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/uiaction.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/valgen.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/validate.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/valnum.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/valtext.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/vidmode.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/vlbox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/vms_x_fix.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/vscroll.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/webview.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/webviewarchivehandler.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/persist/window.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/window.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/windowid.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/withimages.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/wizard.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/wrapsizer.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/wupdlock.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/wxhtml.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_all.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_animatctrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_bannerwindow.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_bmp.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_bmpbt.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_bmpcbox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_bttn.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_cald.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_chckb.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_chckl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_choic.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_choicbk.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_clrpicker.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_cmdlinkbn.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_collpane.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_combo.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_comboctrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_datectrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_dirpicker.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_dlg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_editlbox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_filectrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_filepicker.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_fontpicker.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_frame.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_gauge.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_gdctl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_grid.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_html.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_htmllbox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_hyperlink.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_listb.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_listbk.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_listc.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_mdi.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_menu.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_notbk.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_odcombo.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_panel.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_propdlg.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_radbt.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_radbx.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_scrol.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_scwin.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_sizer.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_slidr.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_spin.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_split.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_srchctrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_statbar.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_stbmp.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_stbox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_stlin.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_sttxt.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_text.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_tglbtn.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_timectrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_toolb.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_toolbk.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_tree.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_treebk.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_unkwn.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xh_wizrd.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xrc/xmlres.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xpmdecod.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/xpmhand.h
)
source_group("Common Headers" FILES ${COMMON_HHEADERS})    

set(SETUP_HHEADERS
    #${CMAKE_CURRENT_SOURCE_DIR}/include/wx/univ/setup.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/wx/msw/setup.h
)
source_group("Setup Headers" FILES ${SETUP_HHEADERS}) 


set(PROJECT_HHEADERS ${MSW_HHEADERS} ${GEN_HHEADERS} ${wxHTML_HHEADERS} ${COMMON_HHEADERS} ${SETUP_HHEADERS})
set(PROJECT_CSOURCES ${COMMON_CSOURCES} ${MSW_CSOURCES} ${GEN_CSOURCES})
# ${wxUniv_HHEADERS} ${wxUniv_CSOURCES}

add_wxlib("${wxCORELIB_NAME}" "${PROJECT_CSOURCES}" "${PROJECT_HHEADERS}" "msw" "_core" "core")

set_target_properties(${wxCORELIB_NAME}
	PROPERTIES 
    COMPILE_FLAGS "-DDLL_EXPORTS -DWXUSINGDLL -DWXMAKINGDLL_CORE -DwxUSE_BASE=0"
)

target_link_libraries(${wxCORELIB_NAME} ${wxBASELIB_NAME} ${TIFFLIB_NAME} ${JPEGLIB_NAME} ${PNGLIB_NAME})

install(TARGETS 
    ${wxCORELIB_NAME}
    RUNTIME DESTINATION bin
    ARCHIVE DESTINATION lib
    LIBRARY DESTINATION lib)
	
install(FILES ${PROJECT_HHEADERS} DESTINATION include)