# - Try to find TinyXML
# Once done, this will define
#
#  TINYXML_FOUND - system has TinyXML
#  TINYXML_INCLUDE_DIR - the TinyXML include directory
#  TINYXML_LIBRARIES - link this to use TinyXML

find_path(TINYXML_INCLUDE_DIR
	NAMES tinyxml2.h
	HINTS
	NO_DEFAULT_PATH
	NO_CMAKE_ENVIRONMENT_PATH
	NO_CMAKE_SYSTEM_PATH
	NO_SYSTEM_ENVIRONMENT_PATH
	NO_CMAKE_PATH
	PATH_SUFFIXES include
	PATHS ${CERBER_GAME_ENGINE_DEPS_DIR}
)

find_library(TINYXML_LIBRARY 
	NAMES tinyxml2
	HINTS
	NO_DEFAULT_PATH
	NO_CMAKE_ENVIRONMENT_PATH
	NO_CMAKE_SYSTEM_PATH
	NO_SYSTEM_ENVIRONMENT_PATH
	NO_CMAKE_PATH
	PATH_SUFFIXES lib
	PATHS ${CERBER_GAME_ENGINE_DEPS_DIR}
)


# First search for d-suffixed libs
find_library(TINYXML_LIBRARY_DEBUG 
	NAMES tinyxml2d
	HINTS
	NO_DEFAULT_PATH
	NO_CMAKE_ENVIRONMENT_PATH
	NO_CMAKE_SYSTEM_PATH
	NO_SYSTEM_ENVIRONMENT_PATH
	NO_CMAKE_PATH
	PATH_SUFFIXES lib
	PATHS ${CERBER_GAME_ENGINE_DEPS_DIR}
)

if(NOT TINYXML_LIBRARY_DEBUG)
	# Then search for non suffixed libs if necessary, but only in debug dirs
	find_library(TINYXML_LIBRARY_DEBUG 
		NAMES tinyxml2
		HINTS
		NO_DEFAULT_PATH
		NO_CMAKE_ENVIRONMENT_PATH
		NO_CMAKE_SYSTEM_PATH
		NO_SYSTEM_ENVIRONMENT_PATH
		NO_CMAKE_PATH
		PATH_SUFFIXES lib
		PATHS ${CERBER_GAME_ENGINE_DEPS_DIR}
	)
endif()

if(TINYXML_LIBRARY)
	if(TINYXML_LIBRARY_DEBUG)
		set(TINYXML_LIBRARIES optimized "${TINYXML_LIBRARY}" debug "${TINYXML_LIBRARY_DEBUG}")
	else()
		set(TINYXML_LIBRARIES "${TINYXML_LIBRARY}")		# Could add "general" keyword, but it is optional
	endif()
endif()

# handle the QUIETLY and REQUIRED arguments and set XXX_FOUND to TRUE if all listed variables are TRUE
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(TINYXML DEFAULT_MSG TINYXML_LIBRARIES TINYXML_INCLUDE_DIR)