# - Try to find RECAST
# Once done, this will define
#
#  RECAST_FOUND - system has RECAST
#  RECAST_INCLUDE_DIR - the RECAST include directory
#  RECAST_LIBRARY - link this to use RECAST

find_path(RECAST_INCLUDE_DIR
	NAMES Recast/Recast.h
	HINTS
	NO_DEFAULT_PATH
	NO_CMAKE_ENVIRONMENT_PATH
	NO_CMAKE_SYSTEM_PATH
	NO_SYSTEM_ENVIRONMENT_PATH
	NO_CMAKE_PATH
	PATH_SUFFIXES include
	PATHS ${CERBER_GAME_ENGINE_DEPS_DIR}
)

find_library(RECAST_LIBRARY 
	NAMES Recast
	HINTS
	NO_DEFAULT_PATH
	NO_CMAKE_ENVIRONMENT_PATH
	NO_CMAKE_SYSTEM_PATH
	NO_SYSTEM_ENVIRONMENT_PATH
	NO_CMAKE_PATH
	PATH_SUFFIXES lib
	PATHS ${CERBER_GAME_ENGINE_DEPS_DIR}
)

# handle the QUIETLY and REQUIRED arguments and set XXX_FOUND to TRUE if all listed variables are TRUE
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(RECAST DEFAULT_MSG RECAST_LIBRARY RECAST_INCLUDE_DIR)