# - Try to find DETOUR
# Once done, this will define
#
#  DETOUR_FOUND - system has DETOUR
#  DETOUR_INCLUDE_DIR - the DETOUR include directory
#  DETOUR_LIBRARY - link this to use DETOUR

find_path(DETOUR_INCLUDE_DIR
	NAMES Detour/DetourCommon.h Detour/DetourNavMesh.h
	HINTS
	NO_DEFAULT_PATH
	NO_CMAKE_ENVIRONMENT_PATH
	NO_CMAKE_SYSTEM_PATH
	NO_SYSTEM_ENVIRONMENT_PATH
	NO_CMAKE_PATH
	PATH_SUFFIXES include
	PATHS ${CERBER_GAME_ENGINE_DEPS_DIR}
)

find_library(DETOUR_LIBRARY 
	NAMES Detour
	HINTS
	NO_DEFAULT_PATH
	NO_CMAKE_ENVIRONMENT_PATH
	NO_CMAKE_SYSTEM_PATH
	NO_SYSTEM_ENVIRONMENT_PATH
	NO_CMAKE_PATH
	PATH_SUFFIXES lib
	PATHS ${CERBER_GAME_ENGINE_DEPS_DIR}
)

# handle the QUIETLY and REQUIRED arguments and set XXX_FOUND to TRUE if all listed variables are TRUE
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(DETOUR DEFAULT_MSG DETOUR_LIBRARY DETOUR_INCLUDE_DIR)